-- Create profile table
CREATE TABLE profile (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  name TEXT DEFAULT 'Mithun T M',
  title TEXT DEFAULT 'Frontend Developer',
  description TEXT,
  email TEXT,
  location TEXT,
  phrases JSONB DEFAULT '["modern web apps.", "responsive UIs.", "seamless experiences.", "React solutions."]'::jsonb,
  stats JSONB DEFAULT '{"cgpa": "8.0", "projects": "10+", "internship": "1"}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  tags JSONB DEFAULT '[]'::jsonb,
  color TEXT DEFAULT '#10B981',
  emoji TEXT DEFAULT '🚀',
  image_url TEXT,
  live TEXT,
  cat TEXT DEFAULT 'Website',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create skills table
CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cat TEXT DEFAULT 'Frontend',
  color TEXT DEFAULT '#10B981',
  icon TEXT DEFAULT 'SiReact',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create contacts table (optional)
CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow everyone to read, only authenticated to write)
CREATE POLICY "Public Read Profile" ON profile FOR SELECT USING (true);
CREATE POLICY "Admin Update Profile" ON profile FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Insert Profile" ON profile FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Public Read Projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Admin All Projects" ON projects FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public Read Skills" ON skills FOR SELECT USING (true);
CREATE POLICY "Admin All Skills" ON skills FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public Insert Contacts" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin Read Contacts" ON contacts FOR SELECT USING (auth.role() = 'authenticated');

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE profile;
ALTER PUBLICATION supabase_realtime ADD TABLE projects;
ALTER PUBLICATION supabase_realtime ADD TABLE skills;

-- Insert initial dummy data for profile
INSERT INTO profile (id, name, title, description, email, location)
VALUES (
  '00000000-0000-0000-0000-000000000000', 
  'Mithun T M', 
  'Frontend Developer', 
  'Frontend Developer with hands-on experience building scalable web applications. Specialized in React.js, JavaScript, and modern CSS to create user-friendly digital experiences with clean UI/UX.',
  'mithunmano0001@gmail.com',
  'Coimbatore, India'
) ON CONFLICT (id) DO NOTHING;
